import type { BeamInput, ColumnInput, ElementInput, ElementType, FootingInput, SlabInput, WallInput } from "@/types/bbs";

const common = { projectName: "Demo RCC Project", concreteGrade: "M25" as const, steelGrade: "Fe500" as const, clearCoverMm: 40, mainBarDiameterMm: 12, stirrupDiameterMm: 8, developmentLengthFactor: 47, lapLengthFactor: 50, hookLengthFactor: 9, bendDeductionRule: "is2502" as const };
const beam: BeamInput = { ...common, elementType: "beam", elementName: "B1", lengthMm: 4500, widthMm: 230, overallDepthMm: 450, effectiveDepthMm: 400, topBars: 2, bottomBars: 3, stirrupZones: [{ label: "Left support", lengthMm: 1000, spacingMm: 100 }, { label: "Mid span", lengthMm: 2500, spacingMm: 150 }, { label: "Right support", lengthMm: 1000, spacingMm: 100 }], extraBars: [{ label: "Extra top support bar", quantity: 2, lengthMm: 1200, diameterMm: 12, anchorageEachEndMm: 300 }], includeCrankedBars: true, crankedBars: 1, crankAngleDeg: 45 };
const slab: SlabInput = { ...common, elementType: "slab", elementName: "S1", clearCoverMm: 20, shortSpanMm: 3200, longSpanMm: 4500, thicknessMm: 150, mainSpacingMm: 150, distributionSpacingMm: 200, supportCondition: "continuous", openings: [{ label: "Pipe sleeve", widthMm: 300, heightMm: 300, count: 1 }] };
const column: ColumnInput = { ...common, elementType: "column", elementName: "C1", widthMm: 300, depthMm: 450, clearHeightMm: 3000, longitudinalBars: 8, tieSpacingMm: 150, lapZoneLengthMm: 900, starterDowelLengthMm: 600 };
const footing: FootingInput = { ...common, elementType: "footing", elementName: "F1", clearCoverMm: 50, lengthMm: 1800, widthMm: 1500, thicknessMm: 450, pedestalLengthMm: 450, pedestalWidthMm: 300, xBarSpacingMm: 150, yBarSpacingMm: 150, includeHooks: true };
const wall: WallInput = { ...common, elementType: "wall", elementName: "W1", clearCoverMm: 30, lengthMm: 5000, thicknessMm: 200, heightMm: 3000, verticalSpacingMm: 200, horizontalSpacingMm: 200, boundaryBarsEachEnd: 4, boundaryBarDiameterMm: 16, openings: [{ label: "Door", widthMm: 900, heightMm: 2100, count: 1 }] };
export function demoInput(type: ElementType): ElementInput { return type === "beam" ? beam : type === "slab" ? slab : type === "column" ? column : type === "footing" ? footing : wall; }
