"use client";
import { useEffect } from "react";
import { useFieldArray, useForm } from "react-hook-form";
import { zodResolver } from "@/lib/forms/zodResolver";
import type { ElementInput, ElementType } from "@/types/bbs";
import { elementSchema } from "@/lib/validation/schemas";
import { demoInput } from "@/lib/calculations/demo";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const diameters = [6, 8, 10, 12, 16, 20, 25, 28, 32, 36, 40];
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1 block text-sm font-semibold text-slate-700">{label}</span>{children}{error && <span className="mt-1 block text-xs text-red-600">{error}</span>}</label>; }

export function InputForm({ elementType, initialInput, onCalculate }: { elementType: ElementType; initialInput?: ElementInput; onCalculate: (input: ElementInput) => void }) {
  const form = useForm<ElementInput>({ resolver: zodResolver(elementSchema), defaultValues: initialInput ?? demoInput(elementType), mode: "onChange" });
  const { register, handleSubmit, reset, control, watch, formState: { errors } } = form;
  const watchedType = watch("elementType");
  useEffect(() => { reset(initialInput ?? demoInput(elementType)); }, [elementType, initialInput, reset]);
  const stirrupZones = useFieldArray({ control, name: "stirrupZones" as never });
  const extraBars = useFieldArray({ control, name: "extraBars" as never });
  const openings = useFieldArray({ control, name: "openings" as never });
  const err = (name: string) => { const parts = name.split("."); let current: unknown = errors; for (const part of parts) current = typeof current === "object" && current !== null ? (current as Record<string, unknown>)[part] : undefined; return typeof current === "object" && current !== null && "message" in current ? String((current as { message?: string }).message) : undefined; };
  return <Card className="print-card"><CardHeader><CardTitle>Input form · {elementType.toUpperCase()}</CardTitle></CardHeader><CardContent><form onSubmit={handleSubmit((data) => onCalculate(data))} className="space-y-6"><div className="grid gap-4 md:grid-cols-4"><input type="hidden" {...register("elementType")} /><Field label="Project name" error={err("projectName")}><Input {...register("projectName")} /></Field><Field label="Element ID" error={err("elementName")}><Input {...register("elementName")} /></Field><Field label="Concrete grade"><Select {...register("concreteGrade")}><option>M20</option><option>M25</option><option>M30</option><option>M35</option><option>M40</option></Select></Field><Field label="Steel grade"><Select {...register("steelGrade")}><option>Fe250</option><option>Fe415</option><option>Fe500</option><option>Fe550</option></Select></Field><Field label="Clear cover (mm)" error={err("clearCoverMm")}><Input type="number" {...register("clearCoverMm")} /></Field><Field label="Main bar dia (mm)" error={err("mainBarDiameterMm")}><Select {...register("mainBarDiameterMm")}>{diameters.map((d) => <option key={d} value={d}>{d}</option>)}</Select></Field><Field label="Stirrup/tie dia (mm)" error={err("stirrupDiameterMm")}><Select {...register("stirrupDiameterMm")}>{diameters.map((d) => <option key={d} value={d}>{d}</option>)}</Select></Field><Field label="Bend rule"><Select {...register("bendDeductionRule")}><option value="is2502">IS 2502 concept</option><option value="site-conservative">Site conservative</option></Select></Field><Field label="Ld factor (×d)" error={err("developmentLengthFactor")}><Input type="number" {...register("developmentLengthFactor")} /></Field><Field label="Lap factor (×d)" error={err("lapLengthFactor")}><Input type="number" {...register("lapLengthFactor")} /></Field><Field label="Hook factor (×d)" error={err("hookLengthFactor")}><Input type="number" {...register("hookLengthFactor")} /></Field></div>{watchedType === "beam" && <BeamFields register={register} err={err} stirrupZones={stirrupZones} extraBars={extraBars} />}{watchedType === "slab" && <SlabFields register={register} err={err} openings={openings} />}{watchedType === "column" && <ColumnFields register={register} err={err} />}{watchedType === "footing" && <FootingFields register={register} err={err} />}{watchedType === "wall" && <WallFields register={register} err={err} openings={openings} />}<div className="flex flex-wrap gap-3"><Button type="submit">Generate / Recalculate BBS</Button><Button type="button" variant="outline" onClick={() => reset(demoInput(elementType))}>Load demo inputs</Button></div></form></CardContent></Card>;
}

type Reg = ReturnType<typeof useForm<ElementInput>>["register"];
type ArrayOps = ReturnType<typeof useFieldArray>;
function BeamFields({ register, err, stirrupZones, extraBars }: { register: Reg; err: (name: string) => string | undefined; stirrupZones: ArrayOps; extraBars: ArrayOps }) { return <Section title="Beam details"><Grid names={["lengthMm", "widthMm", "overallDepthMm", "effectiveDepthMm", "topBars", "bottomBars", "crankedBars"]} labels={["Length", "Width", "Overall depth", "Effective depth", "Top bars", "Bottom bars", "Cranked bars"]} register={register} err={err} /><label className="flex gap-2 text-sm"><input type="checkbox" {...register("includeCrankedBars")} /> Include cranked bars</label><Field label="Crank angle"><Select {...register("crankAngleDeg")}><option value={45}>45</option><option value={60}>60</option></Select></Field><ArrayEditor title="Stirrup spacing zones" array={stirrupZones} fields={["label", "lengthMm", "spacingMm"]} register={register} prefix="stirrupZones" add={{ label: "Zone", lengthMm: 1000, spacingMm: 150 }} /><ArrayEditor title="Extra support bars" array={extraBars} fields={["label", "quantity", "lengthMm", "diameterMm", "anchorageEachEndMm"]} register={register} prefix="extraBars" add={{ label: "Extra", quantity: 1, lengthMm: 1000, diameterMm: 12, anchorageEachEndMm: 300 }} /></Section>; }
function SlabFields({ register, err, openings }: { register: Reg; err: (name: string) => string | undefined; openings: ArrayOps }) { return <Section title="Slab details"><Grid names={["shortSpanMm", "longSpanMm", "thicknessMm", "mainSpacingMm", "distributionSpacingMm"]} labels={["Short span", "Long span", "Thickness", "Main spacing", "Distribution spacing"]} register={register} err={err} /><Field label="Support condition"><Select {...register("supportCondition")}><option value="simply-supported">Simply supported</option><option value="continuous">Continuous</option></Select></Field><ArrayEditor title="Openings" array={openings} fields={["label", "widthMm", "heightMm", "count"]} register={register} prefix="openings" add={{ label: "Opening", widthMm: 300, heightMm: 300, count: 1 }} /></Section>; }
function ColumnFields({ register, err }: { register: Reg; err: (name: string) => string | undefined }) { return <Section title="Column details"><Grid names={["widthMm", "depthMm", "clearHeightMm", "longitudinalBars", "tieSpacingMm", "lapZoneLengthMm", "starterDowelLengthMm"]} labels={["Width", "Depth", "Clear height", "Longitudinal bars", "Tie spacing", "Lap zone length", "Starter/dowel length"]} register={register} err={err} /></Section>; }
function FootingFields({ register, err }: { register: Reg; err: (name: string) => string | undefined }) { return <Section title="Footing details"><Grid names={["lengthMm", "widthMm", "thicknessMm", "pedestalLengthMm", "pedestalWidthMm", "xBarSpacingMm", "yBarSpacingMm"]} labels={["Length", "Width", "Thickness", "Pedestal length", "Pedestal width", "X bar spacing", "Y bar spacing"]} register={register} err={err} /><label className="flex gap-2 text-sm"><input type="checkbox" {...register("includeHooks")} /> Include footing end hooks</label></Section>; }
function WallFields({ register, err, openings }: { register: Reg; err: (name: string) => string | undefined; openings: ArrayOps }) { return <Section title="Wall / NS wall details"><Grid names={["lengthMm", "thicknessMm", "heightMm", "verticalSpacingMm", "horizontalSpacingMm", "boundaryBarsEachEnd", "boundaryBarDiameterMm"]} labels={["Length", "Thickness", "Height", "Vertical spacing", "Horizontal spacing", "Boundary bars each end", "Boundary bar dia"]} register={register} err={err} /><ArrayEditor title="Openings" array={openings} fields={["label", "widthMm", "heightMm", "count"]} register={register} prefix="openings" add={{ label: "Opening", widthMm: 900, heightMm: 2100, count: 1 }} /></Section>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <details open className="rounded-lg border border-slate-200 p-4"><summary className="cursor-pointer font-bold">{title}</summary><div className="mt-4 space-y-4">{children}</div></details>; }
function Grid({ names, labels, register, err }: { names: string[]; labels: string[]; register: Reg; err: (name: string) => string | undefined }) { return <div className="grid gap-4 md:grid-cols-4">{names.map((name, i) => <Field key={name} label={`${labels[i]} (mm/no.)`} error={err(name)}><Input type="number" {...register(name as never)} /></Field>)}</div>; }
function ArrayEditor({ title, array, fields, register, prefix, add }: { title: string; array: ArrayOps; fields: string[]; register: Reg; prefix: string; add: Record<string, string | number> }) { return <div className="rounded-lg bg-slate-50 p-3"><div className="mb-2 flex items-center justify-between"><h4 className="font-semibold">{title}</h4><Button type="button" size="sm" variant="outline" onClick={() => array.append(add as never)}>Add</Button></div>{array.fields.map((field, index) => <div key={field.id} className="mb-2 grid gap-2 md:grid-cols-6">{fields.map((name) => <Input key={name} type={name === "label" ? "text" : "number"} placeholder={name} {...register(`${prefix}.${index}.${name}` as never)} />)}<Button type="button" size="sm" variant="ghost" onClick={() => array.remove(index)}>Remove</Button></div>)}</div>; }
